config/routes.rb
Rails.application.routes.draw do
 
  root 'welcome#index'

  resources :surveys do
    resources :responses
  end


  get 'surveys/:id/input', :to => 'surveys#input'
  get 'search', :to => 'surveys#search'

  post 'surveys/:id/input', :to => 'surveys#add_input'
  post 'search', :to => 'surveys#do_search'

  # resources :users, :only => [:edit, :delete]
  # get 'responses/:id/edit', :to => 'surveys#edit_response', :path => 'responses'
  # post 'responses/:id/edit', :to => 'surveys#update_response'

  get 'welcome/index'

  #devise_for :users, controllers: {
  #      sessions: 'users/sessions'
  #    }

  devise_for  :users, :controllers =>  { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users
  get   '/login', :to => 'sessions#new', :as => :login
  
  # from: http://sourcey.com/rails-4-omniauth-using-devise-with-twitter-facebook-and-linkedin/
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  # TODO: these were changed from 'match', make sure they work with get
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get,:post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get,:post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="container">

  <h1>WordCloud</h1>

  <h3> Browse public surveys </h3>
  <%= link_to "Browse", surveys_path, class: "btn btn-large btn-primary"  %>
  
  <h3> Find a survey </h3>
  <%= form_tag search_path do   %>
  <div class="form-group">
    <%= label_tag :survey_pin %>
    <%= text_field_tag :survey_pin, params[:survey_pin] %>
    <%= submit_tag "Find", class: "btn btn-large btn-primary" %>
  </div>

  <% end %>
  &nbsp
  <% if signed_in? %>
  <h3> Create a new survey </h3>
  <%= link_to "New Survey", new_survey_path, class: "btn btn-large btn-primary"  %>
  <% end %>
</div>