config/routes.rb
Rails.application.routes.draw do
 
  root 'welcome#index'

  resources :surveys do
    resources :responses
  end


  get 'surveys/:id/input', :to => 'surveys#input'
  get 'search', :to => 'surveys#search'

  post 'surveys/:id/input', :to => 'surveys#add_input'
  post 'search', :to => 'surveys#do_search'

  # resources :users, :only => [:edit, :delete]
  # get 'responses/:id/edit', :to => 'surveys#edit_response', :path => 'responses'
  # post 'responses/:id/edit', :to => 'surveys#update_response'

  get 'welcome/index'

  #devise_for :users, controllers: {
  #      sessions: 'users/sessions'
  #    }

  devise_for  :users, :controllers =>  { registrations: 'registrations', omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users
  get   '/login', :to => 'sessions#new', :as => :login
  
  # from: http://sourcey.com/rails-4-omniauth-using-devise-with-twitter-facebook-and-linkedin/
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  # TODO: these were changed from 'match', make sure they work with get
  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get,:post]
  match '/auth/failure', :to => 'sessions#failure', via: [:get,:post]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/survey.rb
# == Schema Information
#
# Table name: surveys
#
#  id            :uuid             not null, primary key
#  closing_time  :datetime
#  survey_pin    :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  max_responses :integer
#  question      :string
#  user_id       :integer
#  is_public     :boolean
#

class Survey < ApplicationRecord
  has_many :responses
  belongs_to :user
  validates :question, length: { minimum: 1, maximum: 1000 }
  
  # callback on the create method so that a PIN gets created only when saved correctly
  before_create do | survey |
    survey_pin = rand(1<<32).to_s(36)
    try_num = 0
    until((!Survey.exists?(:survey_pin => survey_pin)) or try_num < 100)
      survey_pin = rand(1<<32).to_s(36)
      # this just won't happen, but I don't want an infinite loop
      try_num += 1
    end
    survey.survey_pin = survey_pin
  end
end

app/controllers/survey_controller.rb
class SurveyController < ApplicationController
  def index
  end

  # either get here from direct URL or from a search box on the main page, or the survey overview page
  def survey
    @survey = Survey.find(params[:id])
    if @survey.nil?
      flash[:error] = "Survey not found"
      redirect_back_or root_path
    end
  end
  
  def results
  end

  # when users are taking a survey
  def input
    survey_pin = params[:id]
  end

  # when the creator wants to change something in an existing survey
  def admin
  end

  def new
    @survey = Survey.new
  end

  def create
    @survey = Survey.new(survey_params)
    respond_to do | format |
      if @survey.save
        format.html { redirect_to @survey, notice: "Your new survey was created! PIN: #{s.survey_pin}" }
      else
        format.html { render :new }
      end
    end
  end

  private
  def survey_params
    params.require(:open).permit(:duration_days)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  include SessionsHelper
  
  before_action :authenticate, :only => [:edit, :update, :new, :create, :edit_responses, :update_responses]
  before_action :set_survey, :only => [:survey, :show, :input, :add_input, :edit, :update, :check_timeout, :edit_responses, :update_responses]
  before_action :check_public, :only => [:input, :add_input]
  before_action :check_timeout, :only => [:input, :add_input]
  
  def index
    # TODO: return all surveys.  if this is an admin, return all.  If not, return only the pulbic ones.
    # This could get long - need to get the will_paginate gem first
    where_clause = ""
    if signed_in? and current_user.admin?
      where_clause = "1 = 1"
    else
      where_clause = "is_public is true"
    end
    @surveys = Survey.where(where_clause).paginate(:page => params[:page])
  end

  # either get here from direct URL or from a search box on the main page, or the survey overview page
  def survey
    # @survey = Survey.find(params[:id])
    if @survey.nil?
      flash[:error] = "Survey not found"
      redirect_back_or root_path
    end
  end
  
  def show
    # @survey = Survey.find(params[:id])
    responses = @survey.responses 
    puts "Response: \n" + responses.map {|r| r.cleaned_entry}.join("\n")
    # s.flat_map {|x| x.split(" ") }.group_by {|w| w}.map {|k,v| [k, v.length]}
    @word_counts = Hash.new(0)
    responses.flat_map {|r| r.cleaned_entry.split(" ")}.each {|word| @word_counts[word] += 1 }
  end

  def do_search
    pin = params[:survey_pin].strip
    if(s = Survey.find_by_survey_pin(pin))
       redirect_to s
    else
      flash[:error] = "No survey with pin: #{params[:survey_pin]} found ... try again"
      redirect_back(fallback_location: root_path)
    end
  end

  def search
    respond_to do | format |
      puts 'rendering search'
      format.html { render :search }
    end
  end
  
  # when users are taking a survey. this corresponds to the 'get' action
  def input
    @survey = Survey.find(params[:id])
  end

  # when users are taking a survey. this corresponds to the 'put' action
  def add_input
    @survey = Survey.find(params[:id])

    input_user = (current_user || helpers.anonymous_user)
    
    @response = Response.new(survey_id: @survey.id, entry: params[:entry], user_id: input_user.id)
    if @response.save
      flash[:notice] = "Thank you for your input!"
      redirect_to @survey
    else
      flash[:error] = "Couldn't add input: #{@response.errors.messages}"
      redirect_back(fallback_location: root_path)
    end
  end

  
  # when the creator wants to change something in an existing survey
  def admin
  end

  def new
    @survey = Survey.new
  end

  def create
    puts survey_params
    # DateTime.parse(survey_params[:closing_time]
    # Using e.g. "01/14/2018 4:30 PM"
    # DateTime.strptime("01/14/2018 04:30 PM", "%m/%d/%Y %I:%M %p")
    closing_time = DateTime.strptime(survey_params[:closing_time], "%m/%d/%Y %I:%M %p")

    max_responses = 1_000_000
    if survey_params.has_key? :max_responses and survey_params[:max_responses] =~ /^\d+/
      max_responses = survey_params[:max_responses]
    else # if survey_params[:max_responses].downcase.include? "no limit"
      max_responses = 1_000_000
    end
    is_public = (survey_params[:is_public] || "true").downcase.strip == 'true'
    @survey = Survey.new(:closing_time => closing_time,
                         :max_responses => max_responses,
                         :is_public => is_public,
                         :question => survey_params[:question])

    # Note that there must be a current_user b/c of the before_action
    @survey.user = current_user
    respond_to do | format |
      if @survey.save
        format.html { redirect_to @survey, notice: "Your new survey was created! PIN: #{@survey.survey_pin}" }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    # @survey = Survey.find(params[:id])
  end

  def edit_responses
    @responses = @survey.responses 
  end

  def update_responses

  end
  
  def update
    # @survey = Survey.find(params[:id])
    # TODO: take the parameters and set new values
    @survey.closing_time = DateTime.strptime(survey_params[:closing_time], "%m/%d/%Y %I:%M %p")
    @survey.question = survey_params[:question]
    
    @survey.is_public = (survey_params[:is_public] || "true").downcase.strip == 'true'
    respond_to do | format |
      if @survey.save
        format.html { redirect_to @survey, notice: "Survey updated" }
      else
        format.html { render :edit }
      end
    end

  end
  
  private
  def survey_params
    params.require(:survey).permit(:is_public,:closing_time, :max_responses, :question)
  end

  def set_survey
    @survey = Survey.find(params[:id])
  end
  
  def authenticate
    # new in rails 5: no need to include individual helpers
    # helpers.
    # TODO: how do we get the application to redirect the user back to the page that they were on??
    deny_access unless signed_in? 
  end

  def check_public
    if current_user.nil? and not @survey.is_public 
      flash[:error] = "You must sign in to add input to that survey"
      store_location
      redirect_to(new_user_session_path)
    end
  end

  def check_timeout
    # @survey = Survey.find(params[:id])
    if @survey.closing_time < Time.now
      flash[:error] = "Survey is closed"
      redirect_to(@survey)
    end
  end

end

app/helpers/survey_helper.rb
module SurveyHelper

  
end

app/views/surveys/_form.html.erb
  <%= form_for(@survey, :html => {:class => "form-horizontal center", :multipart => true}) do |f| %>
  <% if @survey.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>
    
    <ul>
      <% @survey.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="row">
    <div class='col-md-2'>
      <%= f.label :survey_question %>
    </div>
    <div class='col-md-6'>
      <%= f.text_area :question %>
    </div>
  </div>
  &nbsp
    <div class="row">
      <div class='col-md-2'>
	<%= f.label :open_until %>
      </div>
      <div class='col-md-6'>
        <div class='input-group date' id='datetimepicker'>
	  
	  <%= f.text_field(:closing_time, :class => "form-control") %>
          <!-- <input type='text' class="form-control" />  -->
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
    </div>

    <!-- https://eonasdan.github.io/bootstrap-datetimepicker/  -->
    <script type="text/javascript">
      $(function () {
      $('#datetimepicker').datetimepicker({
      defaultDate: "<%= 1.week.from_now.iso8601 %>"
      });
      });
    </script>
<!-- Not yet for the max responses ...
  &nbsp
    <div class="row">
      <div class="col-md-2">
	<%= f.label :max_responses , class: "col-md-1 control-label" %>
      </div>
      <div class="col-md-6">
	<%= f.select(:max_responses, [1] + ((5..50).step(5).to_a).map {|i| i.to_s} + ["No Limit"]) %>
      </div>
    </div>
    -->

    &nbsp    
    <div class="row">
      <div class="col-md-2"> 
	Public <%= f.radio_button 'is_public', "true", checked: true %>
      </div>
      <div class="col-md-2"> 
	Logged in users only <%= f.radio_button 'is_public', "false" %>
      </div>
    </div>
    &nbsp
    <div class="row">
      <div class="actions">
	
	<div class="col-md-6">
	  <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
	</div>
      </div>
    </div>
    <% end %>

app/views/surveys/_survey.html.erb
<tr>
  <td> <%= survey.question %> </td>
  <td> <%= survey.survey_pin %> </td>
  <td> <%= survey.is_public %> </td>
  <td> <%= survey.closing_time %> </td>
  <td> <%= link_to "View", survey, class: "btn btn-large btn-primary"  %> </td>
</tr>

app/views/surveys/admin.html.erb
<h1>Survey#admin</h1>
<p>Find me in app/views/survey/admin.html.erb</p>

app/views/surveys/edit.html.erb
<div class="container">
  <h1>Edit Survey</h1>
  &nbsp
  <%= render 'form' %>
</div>

app/views/surveys/index.html.erb
<div class="container">
  <h1>Surveys</h1>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Survey Question</th>
        <th>PIN</th>
        <th>Public?</th>
	<th>Closing Date</th>
	<th> </th>
      </tr>
    </thead>
    <tbody>
      <% @surveys.each do | s | %> 
      <%=  render s %>
      <% end %>
    </tbody>
    
  </table>
  <%= will_paginate @surveys %>
</div>

app/views/surveys/input.html.erb
<div class="container">
  <h1>Survey</h1>
  <h2> <%= @survey.question %> </h2>
  <%= form_tag survey_path + "/input" do   %>
  <div class="form-group">
    <%= label_tag :response %>
    <%= text_field_tag :entry, params[:entry] %>
    </div>
  <%= submit_tag "Submit", class: "btn btn-large btn-primary" %>
  
  <% end %>
</div>

app/views/surveys/new.html.erb
<div class="container">
  <h1>Create a new Survey</h1>
  &nbsp
  <%= form_for(@survey, :html => {:class => "form-horizontal center", :multipart => true}) do |f| %>
  <% if @survey.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>
    
    <ul>
      <% @survey.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="row">
    <div class='col-md-2'>
      <%= f.label :survey_question %>
    </div>
    <div class='col-md-6'>
      <%= f.text_area :question %>
    </div>
  </div>
  &nbsp
    <div class="row">
      <div class='col-md-2'>
	<%= f.label :open_until %>
      </div>
      <div class='col-md-6'>
        <div class='input-group date' id='datetimepicker'>
	  
	  <%= f.text_field(:closing_time, :class => "form-control") %>
          <!-- <input type='text' class="form-control" />  -->
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
    </div>

    <!-- https://eonasdan.github.io/bootstrap-datetimepicker/  -->
    <script type="text/javascript">
      $(function () {
      $('#datetimepicker').datetimepicker({
      defaultDate: "<%= 1.week.from_now.iso8601 %>"
      });
      });
    </script>
<!-- Not yet for the max responses ...
  &nbsp
    <div class="row">
      <div class="col-md-2">
	<%= f.label :max_responses , class: "col-md-1 control-label" %>
      </div>
      <div class="col-md-6">
	<%= f.select(:max_responses, [1] + ((5..50).step(5).to_a).map {|i| i.to_s} + ["No Limit"]) %>
      </div>
    </div>
    -->

    &nbsp    
    <div class="row">
      <div class="col-md-2"> 
	Public <%= f.radio_button 'is_public', "true", checked: true %>
      </div>
      <div class="col-md-2"> 
	Logged in users only <%= f.radio_button 'is_public', "false" %>
      </div>
    </div>
    &nbsp
    <div class="row">
      <div class="actions">
	
	<div class="col-md-6">
	  <%= f.submit "Create!", class: "btn btn-default btn-primary" %>
	</div>
      </div>
    </div>
    <% end %>
</div>

app/views/surveys/results.html.erb
<h1>Survey#results</h1>
<p>Find me in app/views/survey/results.html.erb</p>

app/views/surveys/search.html.erb
<div class="container">
  <%= form_tag search_path do   %>
  <div class="form-group">
    <%= label_tag :survey_pin %>
    <%= text_field_tag :survey_pin, params[:survey_pin] %>
    <%= submit_tag "Find", class: "btn btn-large btn-primary" %>
  </div>
  
  <% end %>
</div>

app/views/surveys/show.html.erb
<script type="text/javascript">
      /*!
       * Create an array of word objects, each representing a word in the cloud
       */
      var word_array = [
      <%= raw(@word_counts.map {| word,count | "{text: \"#{word}\", weight: \"#{count}\"}" }.join(",")) %>
      ];

      $(function() {
        // When DOM is ready, select the container element and call the jQCloud method, passing the array of words as the first argument.
        $("#wordcloud").jQCloud(word_array);
      });
</script>

<div class="container" >
  <h3> Survey <i> <%= @survey.survey_pin %> </i></h3>
  <!-- TODO put word cloud here -->
  <h2> <%= @survey.question %> </h2>
  <p>
    <!-- You should explicitly specify the dimensions of the container element -->
    <% if @survey.responses.length > 0 %>
    <div id="wordcloud" style="width: 550px; height: 350px;"></div>
   
  <p>
  <h4>Word Counts</h4>
  <table class="table">
    <thead class="thead-light">
      <tr>
	<th scope="col">Rank</th>
	<th scope="col">Word</th>
	<th scope="col">Count</th>
      </tr>
    </thead>
    <tbody>
      <% sorted_words = @word_counts.keys.sort {|a,b| @word_counts[b] <=> @word_counts[a]} %>
      <% sorted_words.first(10).each_with_index do | word,pos | %>
      <tr>
	<th scope="row"><%= pos + 1 %></th>
	<td><%= word %></td>
	<td><%= @word_counts[word] %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
   <% else %>
    <h3> <i> No responses yet. </i> </h3>
    <% end %>
    <% if  @survey.closing_time > Time.now %>

    <!-- original kludge
    <%= link_to 'Add input', survey_path + "/input", :class => "btn btn-default btn-primary" %>
    -->
    
    <%= link_to 'Add input', new_survey_response_path(@survey), :class => "btn btn-default btn-primary" %>
    <% end %>

    <% if  signed_in? and current_user.admin? %>
    <%= link_to 'Edit Survey', edit_survey_path, :class => "btn btn-default btn-primary" %>
    
    <%= link_to 'All Responses', survey_responses_path(@survey), :class => "btn btn-default btn-primary" %>
    <% end %>

</div>